### PR TITLE
For privacy's sake, convert last names to initials.

### PR DESCRIPTION
**Pull request by Tribex**
Just makes me a bit more comfortable with signing it.

Also, due my editor, contains some code style changes. (Clears empty lines and possibly changes quotes from double to single.)

### CODE REVIEW

**Comment by Nateowami** [comment]
That's a good idea. Though people *could* input it that way themselves, though it would be a tad awkward to say "first name and last initial."

I'll deploy this as soon as I have a chance.

What will happen if people input only first names, or only last names, or first name and last initial, as will likely happen when they see they're displayed that way?

**Comment by Tribex** [comment]
Only First Names: First Name Displayed Fully ['Thomas' -> 'Thomas']
Only Last Names: Last Name Displayed Fully ['Lancer' -> 'Lancer]
First Name and Last Initial: First Name Displayed Fully, Last Initial Displayed ['Thomas L' -> 'Thomas L.']

Only unhandled edge case would be:
['Thomas L.' -> 'Thomas L..']
I should take a look at that.

**Comment by Tribex** [comment]
Somehow I've started Using Capitals Everywhere. Must be getting late. O.o

**Comment by Nateowami** [comment]
I deployed it and it started serving 500 error. Just rolled back. One moment for details.

**Comment by Nateowami** [comment]
Here's the log:

```
Listening on port 3002...
TypeError: Cannot call method 'toUpperCase' of undefined
    at Object.nameToFirstAndInitial (/home/nate/dearkasich/dearkasich/index.js:18:8)
    at eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:100)
    at prog (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at execIteration (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
    at main (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:734:16
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.handlebars.render (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:724:10)
104.237.155.44 - - [30/Mar/2016:02:28:02 +0000] "GET / HTTP/1.1" 500 333 "-" "Mozilla/5.0 (X11; CrOS armv7l 7834.60.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.95 Safari/537.36"
TypeError: Cannot call method 'toUpperCase' of undefined
    at Object.nameToFirstAndInitial (/home/nate/dearkasich/dearkasich/index.js:18:8)
    at eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:100)
    at prog (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at execIteration (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
    at main (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:734:16
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.handlebars.render (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:724:10)
104.237.155.44 - - [30/Mar/2016:02:28:05 +0000] "GET / HTTP/1.1" 500 333 "-" "Mozilla/5.0 (X11; CrOS armv7l 7834.60.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.95 Safari/537.36"
TypeError: Cannot call method 'toUpperCase' of undefined
    at Object.nameToFirstAndInitial (/home/nate/dearkasich/dearkasich/index.js:18:8)
    at eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:100)
    at prog (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at execIteration (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
    at main (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:734:16
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.handlebars.render (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:724:10)
104.237.155.44 - - [30/Mar/2016:02:28:07 +0000] "GET / HTTP/1.1" 500 333 "-" "Mozilla/5.0 (X11; CrOS armv7l 7834.60.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.95 Safari/537.36"
TypeError: Cannot call method 'toUpperCase' of undefined
    at Object.nameToFirstAndInitial (/home/nate/dearkasich/dearkasich/index.js:18:8)
    at eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:100)
    at prog (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at execIteration (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
    at main (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:734:16
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.handlebars.render (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:724:10)
208.126.53.54 - - [30/Mar/2016:02:28:52 +0000] "GET / HTTP/1.1" 500 333 "https://github.com/Nateowami/Dear-Kasich" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36"
TypeError: Cannot call method 'toUpperCase' of undefined
    at Object.nameToFirstAndInitial (/home/nate/dearkasich/dearkasich/index.js:18:8)
    at eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:100)
    at prog (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at execIteration (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
    at main (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:734:16
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.handlebars.render (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:724:10)
208.126.53.54 - - [30/Mar/2016:02:28:55 +0000] "GET / HTTP/1.1" 500 333 "https://dearkasich.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36"
TypeError: Cannot call method 'toUpperCase' of undefined
    at Object.nameToFirstAndInitial (/home/nate/dearkasich/dearkasich/index.js:18:8)
    at eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:100)
    at prog (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at execIteration (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
    at main (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:734:16
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.handlebars.render (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:724:10)
208.126.53.54 - - [30/Mar/2016:02:28:57 +0000] "GET / HTTP/1.1" 500 333 "https://dearkasich.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36"
TypeError: Cannot call method 'toUpperCase' of undefined
    at Object.nameToFirstAndInitial (/home/nate/dearkasich/dearkasich/index.js:18:8)
    at eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:100)
    at prog (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at execIteration (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
    at main (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:734:16
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.handlebars.render (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:724:10)
208.126.53.54 - - [30/Mar/2016:02:28:58 +0000] "GET / HTTP/1.1" 500 333 "https://dearkasich.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36"
TypeError: Cannot call method 'toUpperCase' of undefined
    at Object.nameToFirstAndInitial (/home/nate/dearkasich/dearkasich/index.js:18:8)
    at eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:100)
    at prog (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
    at execIteration (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
    at Object.<anonymous> (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
    at Object.eval (eval at createFunctionContext (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:5:31)
    at main (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (/home/nate/dearkasich/dearkasich/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:734:16
    at /home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:474:18)
    at new Promise (/home/nate/dearkasich/dearkasich/node_modules/consolidate/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.handlebars.render (/home/nate/dearkasich/dearkasich/node_modules/consolidate/lib/consolidate.js:724:10)
208.126.53.54 - - [30/Mar/2016:02:28:58 +0000] "GET / HTTP/1.1" 500 333 "https://dearkasich.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36"
error: Forever detected script exited with code: null
```

**Comment by Tribex** [comment]
Odd, "Works on My Machine (TM)"
NPM version?

**Comment by Nateowami** [comment]
Works on mine too, just not in production. NPM `1.3.10`

**Comment by Tribex** [comment]
Yeah, NPM version is irrelevant (Thought it might be handlebars failing to be required due to a nested dependency), though that's an ANCIENT version of NPM.

Somehow splitName is an array with a length greater than 1, but the second item is undefined. How?

**Comment by Tribex** [comment]
New commit should fix it, though I'll probably need to open a new PR.

**Comment by Nateowami** [comment]
Thanks. I've deployed it. Several names (I'm looking at your brothers especially) had trailing white space, which tripped it up. I just added the `trim()` function in a7da63727fb38ad3addb41c45a5d8497fb938140.

**Comment by Tribex** [comment]
Oh, I see. Silly peoples.

**Comment by Nateowami** [comment]
That explains where the `TypeError: Cannot call method 'toUpperCase' of undefined` came from. `"First Last ".split(' ')` yields `["First", "Last", ""]`. Then `["First", "Last", ""][2][0]` is `undefined`, and and throws an exception when you call `toUpperCase()`.

Your brothers crashed my server. Tell them to get their lawyers ready. :stuck_out_tongue_winking_eye: 

Actually, it's a good thing they (and a couple others) did that, or the first person who did would have crashed the server. And I wouldn't have discovered it immediately, and would have wondered what was wrong.

**Comment by Tribex** [comment]
Yep, makes sense. My bad for not considering such a case at the start.

**Pull request merged**
